### ISSUE TITLE
Basic Implementation

### ISSUE THREAD

**Issue by leeshengcian** [leeshengcian/Polygon-Clipping#2]
@yungyuc I've finish the basic implementation of Polygon clipping.
My initial idea is feeding two input data in the system, which is polygon data and clipping area data,
as I mentioned in the proposal, I hope to optimize the original sutherland-hodgman by giving a rather
complex data.
Is it ok that I make both input data to be polygon with N vertices, where N is a big number?

**Comment by yungyuc** [comment]
How large N you would like it to be?  You may also make a drawing for discussion.

**Comment by leeshengcian** [comment]
Probably something like this, but with bigger amount of vertex
<img width="680" alt="image" src="https://github.com/leeshengcian/Polygon-Clipping/assets/145427848/90d3f55a-55f9-4a7a-902d-c5de08287a1b">

**Comment by leeshengcian** [comment]
this example illustrate more precisely
<img width="532" alt="image" src="https://github.com/leeshengcian/Polygon-Clipping/assets/145427848/bf1b0b28-a2e6-406c-b869-247243da8e53">

**Comment by yungyuc** [comment]
> Probably something like this, but with bigger amount of vertex <img alt="image" width="680" src="https://user-images.githubusercontent.com/145427848/285402644-90d3f55a-55f9-4a7a-902d-c5de08287a1b.png">

Good schematics.  But you did not answer my question.  "Bigger" does not describe how large you want the number to be.  Please evaluate.

**Comment by yungyuc** [comment]
BTW, never write `using namespace std;` anywhere: https://github.com/leeshengcian/Polygon-Clipping/blob/f9b41d9f67d588ceff8fb080cf7f5065cc8a72f4/PolyClip.cpp#L3

I am not sure why any serious software development team would like to hire someone writing code like that.

**Comment by leeshengcian** [comment]
I don't have a precise range of number the polygon should have, 
because I don't know for sure that how large N is can distinguish the performance 
between original algorithm and optimized one

**Comment by leeshengcian** [comment]
> BTW, never write `using namespace std;` anywhere:
> 
> https://github.com/leeshengcian/Polygon-Clipping/blob/f9b41d9f67d588ceff8fb080cf7f5065cc8a72f4/PolyClip.cpp#L3
> 
> I am not sure why any serious software development team would like to hire someone writing code like that.

Thanks for remind, I will keep in mind!

**Comment by yungyuc** [comment]
> I don't have a precise range of number the polygon should have, because I don't know for sure that how large N is can distinguish the performance between original algorithm and optimized one

Give me an order of magnitude

**Comment by leeshengcian** [comment]
How about I set N to be like 500, and test the performance between two algorithms
If there's not much differences, I increase the magnitude

**Comment by yungyuc** [comment]
500 is too small to see any difference in runtime but too large for you to visually check for program error.  I recommend you to start with 10-100 vertices to make sure your algorithm is correct and then move forward.

**Comment by leeshengcian** [comment]
Sure, then I'll be focusing on correctness of algorithm first

**Comment by yungyuc** [comment]
Sounds good.  If you think the discussion reaches a conclusion, close the issue.
